AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata: 

Parameters: 
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: Windows file server
    Type: String
    Default: m4.4xlarge
    ConstraintDescription: Designated R5d.12Xlarge as the master node.
  AMIID:
    Description: AMI ID to be used as the base operating system for the Windows file server (Windows server 2016)
    Type: String
    Default: ami-03b3182648d0d0bfb
    ConstraintDescription: Must be the name of an AMI ID such as ami-1234567
  SGID:
    Description: Security group ID
    Type: String
    Default: sg-0c031b59aea4fd249
    ConstraintDescription: Manually enter the security group ID to be used
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: SubnetId of an existing subnet in your
      Virtual Private Cloud (VPC)

Mappings: 

Conditions: 

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref 'AMIID'
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyName'
      KeyName: 
      DisableApiTermination: 
      Monitoring: true|false
      SubnetId: !Ref 'SubnetId'
      SecurityGroupIds: !Ref 'SGID'
      Userdata: !Base64 |
      <powershell> 
      "New-Item -Path D:\petrel  -ItemType Container",
      "New-SmbShare -Path D:\petrel -Name petrel"
      </powershell>
      Tags:
        - Key: key
          Value: value
      BlockDeviceMappings:
      -
        DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 200
        DeviceName: /dev/xvdf
        Ebs: 
          VolumeSize: 16000 

Outputs: